channels:
    - conda-forge
dependencies:
    - black
    - dask-core
    - distributed
    - ipywidgets
    - isort
    - jupyter-server-proxy
    - jupyterlab-git
    - jupyterlab
    - jupyter_ydoc
    - jupyterlab-nvdashboard
    - nbconvert
    - nbdime
    - nodejs
    - notebook
    - pip
    - pyviz_comms
    - tornado
    - voila
    - yarl
    - sqlite=3.51.1
    - libsqlite=3.51.1
    - pip:
        - jupyter_server
        - jupyter_bokeh
        - jupyterlab_code_formatter
        - jupyterlab_execute_time
        - jupyterlab_widgets
