channels:
- https://conda.saturncloud.io/pkgs
- pytorch
- defaults
dependencies:
- blas=*=mkl
- nodejs=10.13.0
- python=3.7
- numpy=1.16.4
- pandas=0.24.2
- ipywidgets=7.2*
- numexpr
- matplotlib
- scipy
- seaborn
- scikit-learn
- scikit-image
- sympy
- cython
- patsy
- statsmodels
- cloudpickle
- dill
- numba
- bokeh
- sqlalchemy
- hdf5
- h5py
- vincent
- beautifulsoup4
- protobuf
- xlrd
- ipykernel
- dask=2.8.1
- lz4
- graphviz
- s3fs
- dash
- dash-bootstrap-components
- dash-core-components
- dash-daq
- dash-html-components
- dash-renderer
- dash-table
- pip
- s3fs
- nltk
- gensim
- wordcloud
- pytorch-cpu
- torchvision-cpu
- tensorflow=1.14.0=mkl_py37h45c423b_0
- cvxpy
- keras
- pip:
  - tweepy
  - geopandas==0.5.1
  - descartes==1.1.0
  - pyproj==2.2.1
name: saturn