channels:
  - defaults
  - conda-forge
  - https://conda.saturncloud.io/pkgs
  - saturncloud
dependencies:
  - nodejs=11
  - python=3.7
  - ipywidgets
  - jupyterlab=2.0.1
  - nbconvert
  - notebook
  - jupyterhub=1.0.0.devsaturn2
  - nbserverproxy
  - tornado=5.0
  - jupyter_saturn=${JUPYTER_SATURN_VERSION}
  - nbdime
  - pyyaml
  - voila
